apiVersion: batch/v1
kind: Job
metadata:
  name: model-aggregation-job

spec:
  template:
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: model-training
        image: mikewahousekey/ml-python-snapshot:latest
        env:
          - name: POSTGRES_TOKEN          
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: POSTGRES_TOKEN
        command:
          - /bin/bash
          - -c
          - |
            mc alias set myminio http://minio-service:9000 minioadmin minioadmin && \

            mc ls myminio/models --recursive | \
                sort -k 1,1 -k 2,2 -k 3,3 | \
                tail -n 1 | \
                awk '{print $NF}' | \
                xargs -I {} mc cp myminio/models/{} /app/models/

            python testModel/testModel.py

            mc cp /app/models/upload/* myminio/models

            rm -rf /app/models/*
            
        volumeMounts:
        - mountPath: /app/models
          name: model-volume              # Mount the PVC to access models

      volumes:                            
      - name: model-volume                # PVC to access to models
        persistentVolumeClaim:
          claimName: model-pvc

      restartPolicy: OnFailure
