apiVersion: batch/v1
kind: Job
metadata:
  name: model-aggregation-job

spec:
  template:
    spec:
      containers:
      - name: model-aggregation
        image: mikewahousekey/ml-python-snapshot:latest
        command:
          - /bin/bash
          - -c
          - |
            apt-get update && \
            apt-get install curl -y && \

            curl -O https://dl.min.io/client/mc/release/linux-amd64/mc && \
            chmod +x mc && \
            mv mc /usr/local/bin/ && \

            mc alias set myminio http://minio-service:9000 minioadmin minioadmin && \

            mc ls myminio/models --recursive | \
                sort -k 1,1 -k 2,2 -k 3,3 | \
                tail -n 1 | \
                awk '{print $NF}' | \
                xargs -I {} mc cp myminio/models/{} /models/

            python scripts/testModel.py

            mc cp models/upload/* myminio/models

            rm -rf /models/*

            tail -f /dev/null

        volumeMounts:
        - mountPath: /scripts
          name: script-volume             # Mount script from ConfigMap
        - mountPath: /models
          name: model-volume              # Mount the PVC to access models

      volumes:                            
      - name: script-volume               # Access for script folder
        configMap:
          name: script-volume
          
      - name: model-volume                # PVC to access to models
        persistentVolumeClaim:
          claimName: model-pvc

      restartPolicy: OnFailure
