apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  
spec:
  parallelism: 2  # Number of parallel pods
  completions: 3  # Total number of pods to complete

  template:
    spec:
      containers:
      - name: model-training
        image: mikewahousekey/ml-python-snapshot:latest
        
        resizePolicy:
        - resourceName: cpu
          restartPolicy: NotRequired       # Resize CPU without restarting the container
        - resourceName: memory
          restartPolicy: RestartContainer   # Resize memory requires restarting the container

        command:
          - /bin/sh
          - -c
          - |
            python /script/randomForest.py
  
        resources:
          requests:
            cpu: "256m"
            memory: "256Mi"
          limits:
            cpu: "512m"
            memory: "512Mi"

        volumeMounts:
        - mountPath: /script
          name: script-volume             
        - mountPath: /models
          name: model-volume              

      volumes:
      - name: script-volume
        configMap:
          name: script-volume 

      - name: model-volume                
        persistentVolumeClaim:
          claimName: model-pvc

      restartPolicy: OnFailure

---

apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: model-training-job-vpa
spec:
  targetRef:
    apiVersion: "batch/v1"
    kind: Job
    name: model-training-job
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
    - containerName: model-training
      minAllowed:
        cpu: "128m"
        memory: "128Mi"
      maxAllowed:
        cpu: "1"
        memory: "1Gi"
      controlledResources: ["cpu", "memory"]