apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  
spec:
  parallelism: 2  # Number of parallel pods
  completions: 2  # Total number of pods to complete

  template:
    spec:
      containers:
      - name: model-training
        image: mikewahousekey/ml-python-snapshot:latest

        # Code for running the script to build the model
        command:
          - /bin/sh
          - -c
            # tail -f /dev/null
          - |
            python /script/randomForest.py


        volumeMounts:
        - mountPath: /script
          name: script-volume             # Mount script from ConfigMap
        - mountPath: /models
          name: model-volume              # Mount the PVC to save models

      volumes:                            # Access to script folder
      - name: script-volume
        configMap:
          name: script-volume 

      - name: model-volume                # PVC to store models
        persistentVolumeClaim:
          claimName: model-pvc

      restartPolicy: OnFailure
