# persistent-volume.yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: model-pv
  
spec:
  capacity:
    storage: 1Gi  # Storage size
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: /mnt/data/models  # Local directory on the node (adjust as needed)
    type: Directory
