apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  
spec:
  parallelism: 4  # Number of parallel pods
  completions: 4  # Total number of pods to complete

  template:
    spec:
      containers:
      - name: model-training
        image: mikewahousekey/ml-python-snapshot:latest

        # Code used for deploying
        command:
          - /bin/sh
          - -c
            # python /script/randomforest.py  # Run training script
            # cp model.pkl /models/model_${HOSTNAME}.pkl  # Save model to PVC
          - |
            tail -f /dev/null


        volumeMounts:
        - mountPath: /script
          name: script-volume             # Mount script from ConfigMap
        - mountPath: /models
          name: model-volume              # Mount the PVC to save models

      volumes:                            # Access to script folder
      - name: script-volume
        configMap:
          name: script-volume 

      - name: model-volume                # PVC to store models
        persistentVolumeClaim:
          claimName: model-pvc

      restartPolicy: OnFailure
