apiVersion: batch/v1
kind: Job
metadata:
  name: model-training-job
  
spec:
  parallelism: 4  # Number of parallel pods
  completions: 4  # Total number of pods to complete

  template:
    spec:
      containers:
      - name: model-training
        image: mikewahousekey/ml-python-snapshot:latest

        # tail -f /dev/null
        # Code used for deploying
        command:
          - /bin/sh
          - -c
          - |
            python /script/randomforest.py  # Run training script
            cp model.pkl /models/model_${HOSTNAME}.pkl  # Save model to PVC

        volumeMounts:
        - mountPath: /script
          name: script-volume  # Mount the randomforest.py script from ConfigMap
        - mountPath: /models
          name: model-volume  # Mount the PVC to save models

      volumes:
      - name: script-volume
        configMap:
          name: script-volume  # ConfigMap for randomforest.py

      - name: model-volume
        persistentVolumeClaim:
          claimName: model-pvc  # PVC to store models

      restartPolicy: OnFailure
