apiVersion: batch/v1
kind: Job
metadata:
  name: rf-model-training
spec:
  parallelism: 4  # Number of parallel pods
  completions: 4  # Total number of pods to complete
  template:
    spec:
      containers:
      - name: rf-container
        image: wohousekey/randomforest:latest
        args: ["python", "/app/randomForest.py"]
      restartPolicy: Never
