apiVersion: v1
kind: Service
metadata:
  name: express-service
spec:
  selector:
    app: express-app       # Matches the app label in the Deployment
  ports:
    - name: express-port
      protocol: TCP
      port: 3030           # Cluster-internal port
      targetPort: 3030     # Port in the container
      nodePort: 31030     # Port on the local machine
  type: NodePort            # Exposes the service on a node's IP and the specified nodePort
