apiVersion: v1
kind: Service
metadata:
  name: mlflow-server
spec:
  selector:
    app: mlflow
  ports:
    - name: api-port
      protocol: TCP
      port: 5000        # Cluster API port
      targetPort: 5000  # Pod API port
      nodePort: 30005  # Local machine API port (for external access)
  type: NodePort  # Use NodePort to expose the service on your local machine
