apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow

    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow
          ports:
            - containerPort: 5000

          env:
            # Target to run the server
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-server:5000"

            # MinIO S3 configuration
            - name: MLFLOW_ARTIFACT_URI
              value: "s3://minio-service/mlflow-artifacts"
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"  # MinIO's default access key
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"  # MinIO's default secret key
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio-service:9000"  # MinIO endpoint URL (adjust if different)

          # Install boto3 after container starts
          lifecycle:
            postStart:
              exec:
                command:
                  - "/bin/sh"
                  - "-c"
                  - "pip install boto3"

          # Command to run the MLflow server
          command: [
            "mlflow", "server",
            "--backend-store-uri", "/mlflow-server/mlruns",
            "--default-artifact-root", "s3://mlflow-artifacts",
            "--host", "0.0.0.0",
            "--port", "5000"
          ]

          volumeMounts:
            - name: mlflow-storage
              mountPath: /mlflow-server/mlruns

      volumes:
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc
