apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow-server
  labels:
    app: mlflow

spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow

    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow
          ports:
            - containerPort: 5000

          env:
            # Target to run the server
            - name: MLFLOW_TRACKING_URI
              value: "http://mlflow-server:5000"

            - name: MLFLOW_ARTIFACT_URI
              value: "s3://minio-service/mlflow-artifacts"
            - name: AWS_ACCESS_KEY_ID
              value: "minioadmin"
            - name: AWS_SECRET_ACCESS_KEY
              value: "minioadmin"

          # Command to rewrite the existing format
          command: [
            "mlflow", "server",
            "--backend-store-uri", "/mlflow-server/mlruns",
            "--default-artifact-root", "s3://minio-service/mlflow-artifacts",
            "--host", "0.0.0.0",
            "--port", "5000"
          ]
          
          volumeMounts:
            # Name of the volume (can be anything as its a temp variable)
            - name: mlflow-storage
              # folder in which it will save/load the data
              mountPath: /mlflow-server/mlruns

      volumes:
        # Have to be the same name as being mounted
        - name: mlflow-storage
          persistentVolumeClaim:
            claimName: mlflow-pvc

