apiVersion: v1
kind: Service
metadata:
  name: minio-service
spec:
  selector:
    app: minio
  ports:
    - name: api-port
      protocol: TCP
      port: 9000        # Cluster API port
      targetPort: 9000  # Pod API port
      nodePort: 30000   # Local machine API port
    - name: console-port
      protocol: TCP
      port: 9900        # Cluster Console port
      targetPort: 9900  # Pod Console port
      nodePort: 30001   # Local machine Console port
  type: NodePort
